    global:
      resolve_timeout: 1m
    route:
      group_wait: 10s
      group_interval: 30s
      repeat_interval: 10s
      receiver: "telegram"
      routes:
        - receiver: "telegram"
          group_wait: 10s
          match_re:
            severity: "critical"
          continue: true
    receivers:
      - name: "telegram"
        telegram_configs:
          - send_resolved: true
            bot_token: '5933756043:AAE8JLL5KIzgrNBeTP5e-1bkbJy4YRoeGjs'
            chat_id: -1001634310929
