---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: gitlab.praktikum-services.ru:5050/std-019-002/sausage-store/sausage-frontend-nginx:latest
          imagePullPolicy: Always
          ports:
            - name: frontend
              containerPort: 80
          volumeMounts:
            - name: nginx-config-volume
              mountPath: /etc/nginx/conf.d
            - name: docker-socket
              mountPath: /tmp/docker.sock
      volumes:
        - name: nginx-config-volume
          configMap:
            name: nginx-config-frontend
        - name: docker-socket
          hostPath:
            path: /var/run/docker.sock
      imagePullSecrets:
        - name: docker-config-secret
