---
apiVersion: v1
kind: Secret
metadata:
  name: vault
  labels:
    app: vault
data:
  vault_token: aHZzLjBTR1hDcTQxYUlhV3hRSGl0ekFHM3FHTAo=
  vault_host: aHR0cDovL3N0ZC0wMTktMDIucHJha3Rpa3VtLXNlcnZpY2VzLnRlY2g6ODIwMC8=
type: Opaque
---
kind: Secret
apiVersion: v1
metadata:
  name: docker-config-secret
data:
  .dockerconfigjson: >-
    ewoJImF1dGhzIjogewoJCSJnaXRsYWIucHJha3Rpa3VtLXNlcnZpY2VzLnJ1OjUwNTAiOiB7CgkJCSJhdXRoIjogImMzUmtMVEF4T1Mwd01ESTZWak5pTkRsdE5sZz0iCgkJfQoJfQp9
type: kubernetes.io/dockerconfigjson
