---
groups:
  - name: Sausage store rules
    rules:
    - alert: InstanceDown
      expr: up{app="backend"} == 0
      for: 10s
      labels:
        severity: critical
        project: "sausage_store"
        component: "Backend"
