groups:
- name: successful_get
  rules:
  - alert: SuccessfulGETRequest
    expr: http_server_requests_seconds_count{method="GET", status="200", uri="/api/products"} > 0
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: "Successful GET request on /api/products"
