stages:
  - deploy

deploy:
  stage: deploy
  script:
    - mkdir ~/.kube
    - echo $KUBECONFIG > ~/.kube/config
    - pwd
    - cd /src/yandex/practicum/kubernetes/backend && kubectl apply -f .
    - cd ../backend-report && kubectl apply -f .
    - cd ../frontend && kubectl apply -f .
    - cd ../ingress && kubectl apply -f .
    - rm -f $HOME/.kube/config
  only:
    changes:
      - src/yandex-practicum/kubernetes/**/* 
  environment:
    name: sausage-store-url # Замените на свое имя
    url: https://rayumov-valery-19.k8s.praktikum-services.tech 
