---
apiVersion: v1
kind: Secret
metadata:
  name: vault
  labels:
    app: vault
data:
  vault_token: {{ .Values.vault_token }}
  vault_host: {{ .Values.vault_host }}
type: Opaque
---
kind: Secret
apiVersion: v1
metadata:
  name: docker-config-secret
data:
  .dockerconfigjson: {{ .Values.dockerconfigjson }}
type: kubernetes.io/dockerconfigjson
---
apiVersion: v1
kind: Secret
metadata:
  name: db
  labels:
    app: backend
data:
  url: {{ .Values.url }}
  username: {{ .Values.username }}
  password: {{ .Values.password }}
  mongo_url: {{ .Values.mongo_url }}
type: Opaque
---
