---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: backend
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: backend
  updatePolicy:
    updateMode: "Auto"
  resourcePolicy:
    containerPolicies:
      - containerName: "*"
        minAllowed:
          cpu: {{ .Values.minCpu }}
          memory: {{ .Values.minMem }}
        maxAllowed:
          cpu: {{ .Values.maxCpu }}
          memory: {{ .Values.maxMem }}
        controlledResources: ["cpu", "memory"]
        controlledValues: RequestsAndLimits
